---
title: "Hola, soy Noé Olivera"
site: distill::distill_website
---

<head>
<title>-> Noé Olivera</title>
</head>

<div>
<div
<p>Soy economista hondureño</p>
<p>Hago visualizaciones de las principales variables economicas del país.</p>
<p>Este es mi sitio web personal donde comparto...</p>
<ul>
<li>Comparto las <a href="https://github.com/Nolivera007/data_visualization">visualizaciones</a> que hago con ggplot2</li>
<li>Comparto el desarrollo de un <a href="https://github.com/Nolivera007/openhn">paquete R</a> de datos para facilitar el uso de R</li>
<li>Comparto una lista en Notion de los <a href="https://www.notion.so/7e1226a54ab74a69b95d373bc5ea8af4?v=9aa4589b80cb4d789c296819d679a652">libros</a> que actualmente estoy leyendo sobre economía, econometría, ciencia de datos y otros temas.</li>
</ul>
</div>
<<<<<<< HEAD
  

  <div class = "pull-right">
Soy economista, apasionado por la economía, interesado en la econometría aplicada y entusiasta de la ciencia de datos. También me interesa el mundo del [Open Source](https://en.wikipedia.org/wiki/Open_source). Este es mi sitio personal donde comparto el trabajo que realizo en mis [proyectos personales](https://github.com/Nolivera007/data_visualization), principalmente visualización de datos con [ggplot2](https://ggplot2.tidyverse.org/index.html) y una lista de los [libros](https://www.notion.so/7e1226a54ab74a69b95d373bc5ea8af4?v=9aa4589b80cb4d789c296819d679a652) que me interesan. 

Mis intereses se enfocan en conocer y analizar la situación económica y social de Honduras, América latina y el Caribe. 

_"Without data, you’re just another person with an opinion"_, W. Edwards Deming.
  </div>
=======
>>>>>>> test
</div>

<div>
<<<<<<< HEAD
<div>
<br>

<br>

## Formación
<div class = "container">
  <div class = "pull-left">
### Educación
- Economía | **Universidad Nacional Autónoma de Honduras (UNAH).**

 </div>
  <div class = "pull-right">
### Cursos

- [CS50x: Introduction to Computer Science](https://cs50.harvard.edu/x/2021/) | **Harvard University.**
- [CS50s: Introduction to Artificial Intelligence with Python](https://cs50.harvard.edu/ai/2020/) | **Harvard University.**
- [CS229: Machine Learning](http://cs229.stanford.edu/) | **Stanford.**
  </div>
</div>
<br>

=======
<h2>Proyectos</h2>
<p>
Si estas empezando a utilizar R con el objetivo de facilitar el uso de R estoy desarrollando un paquete de datos R, llamado <a href="https://github.com/Nolivera007/openhn">`openhn`</a> el cual contiene datos económicos y sociales de Honduras.
</p>
</div>
>>>>>>> test
